# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: 
          - framework: 'netstandard2.1'
            publishSingleFile: 'False'
          - framework: 'net8.0'
            publishSingleFile: 'True'

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Get tag
      run: |
        echo "BUILD_NUMBER=$(git rev-list --count ${{ github.ref_name }})" >> $GITHUB_OUTPUT
      id: version

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish k2.healess/LouveSystems.K2.Headless.csproj -c Release -o ${{ github.workspace }}/publish/ --self-contained true -f ${{ matrix.target.framework }} -p PublishSingleFile=${{matrix.target.publishSingleFile}}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target.framework }}.zip
        path: ${{ github.workspace }}/publish/

    - name: Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        files: ${{ github.workspace }}/publish/**
        generate_release_notes: true
        tag_name: r${{ steps.version.outputs.BUILD_NUMBER }}
        release_name: Release r${{ steps.version.outputs.BUILD_NUMBER }}
        draft: false
        prerelease: false